# linter checks syntax , indenatation and code spelling .
name: python-linter

on:
  push:
   paths: "*.py"

jobs:
   code-linter:
     runs-on: ubuntu-latest
     steps:
     - name: clone the code 
       # rather using runs on will use uses:
       uses: actions/checkout@v7
     - name: setup python
       uses: actions/setup-python@v5
       with: 
        python-version: '3.11'
     - name: Install linter
       run: pip install ruff
     - name: check the code 
       run: ruff check .
      
